filegroup(
    name = "isekai_viz",
    srcs = [
        "process_goodput_scalar.py",
        "process_latency_vec.py",
    ],
    tags = ["ignore_srcs"],
    visibility = ["//visibility:private"],
)
